language: go

go:
  -1.x
  - 1.6
  - 1.7

services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/


before_install:
  - go get -v github.com/golang/lint/golint
  - go get -u github.com/FiloSottile/gvt
  - ./testscript.sh
